version: '3.8'

services:
  academic-thesis-ai:
    build: .
    image: academic-thesis-ai:latest
    container_name: academic-thesis-ai

    # Environment variables (override with .env file)
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GPTZERO_API_KEY=${GPTZERO_API_KEY:-}

    # Mount volumes for persistence
    volumes:
      # Input/output directories
      - ./examples:/app/examples
      - ./tests/outputs:/app/tests/outputs
      # User research data
      - ./research:/app/research
      # Environment file (for API keys)
      - ./.env:/app/.env:ro

    # No ports needed for CLI-only usage
    # Uncomment below if you add a web UI later:
    # ports:
    #   - "8501:8501"

    # Default: run tests on startup
    # Override with: docker-compose run --rm academic-thesis-ai bash
    # command: ["python", "tests/test_pdf_engines.py"]

    # Restart policy
    restart: unless-stopped

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  # Optional: Testing service
  test:
    build: .
    image: academic-thesis-ai:latest
    container_name: academic-thesis-ai-test
    volumes:
      - ./tests/outputs:/app/tests/outputs
    command: ["python", "tests/test_pdf_engines.py"]
    profiles:
      - testing

networks:
  default:
    name: academic-thesis-ai-network
